create schema trade_manager;



create table trade_manager.basket_products (
                                               basket_id bigint not null,
                                               product_id bigint not null
);

create table trade_manager.baskets (
                                       client_id bigint not null,
                                       id bigint generated by default as identity,
                                       primary key (id)
);

create table trade_manager.clients (
                                       basket_id bigint unique,
                                       id bigint generated by default as identity,
                                       manager_id bigint,
                                       client_name varchar(255),
                                       primary key (id)
);

create table trade_manager.managers (
                                        id bigint generated by default as identity,
                                        manager_name varchar(255),
                                        primary key (id)
);

create table trade_manager.product_stocks (
                                              quantity integer,
                                              id bigint generated by default as identity,
                                              product_id bigint not null,
                                              primary key (id)
);

create table trade_manager.products (
                                        price numeric(38,2) not null,
                                        id bigint generated by default as identity,
                                        product_name varchar(255),
                                        primary key (id)
);

alter table if exists trade_manager.basket_products
    add constraint FKe4ijn3avfn0c6eqj6w7a2o2gd
        foreign key (product_id)
            references trade_manager.products;

alter table if exists trade_manager.basket_products
    add constraint FK5e2sxbbeynl11h01xnopnkvol
        foreign key (basket_id)
            references trade_manager.baskets;

alter table if exists trade_manager.baskets
    add constraint FKkfm6v8tpljcg2t31hto7jtj7i
        foreign key (client_id)
            references trade_manager.clients;

alter table if exists trade_manager.clients
    add constraint FKiam4tmnbvcrkqnk51grxds3sp
        foreign key (basket_id)
            references trade_manager.baskets;

alter table if exists trade_manager.clients
    add constraint FKb04ux70c9nn0yi4y3pmitlfo9
        foreign key (manager_id)
            references trade_manager.managers;

alter table if exists trade_manager.product_stocks
    add constraint FK1dm90iiym3tkqyivfwcsrmn2k
        foreign key (product_id)
            references trade_manager.products;

