-- INSERT INTO trade_manager.clients (client_name, manager_id)
-- VALUES
--     ('Client 1', 1),
--     ('Client 2', 1),
--     ('Client 3', 2),
--     ('Client 4', 2),
--     ('Client 5', 3),
--     ('Client 6', 3),
--     ('Client 7', 4),
--     ('Client 8', 4),
--     ('Client 9', 5),
--     ('Client 10', 5),
--     ('Client 11', 6),
--     ('Client 12', 6),
--     ('Client 13', 7),
--     ('Client 14', 7),
--     ('Client 15', 8);